avatar: /images/avatar4.jpg # 网站 Logo
background: /images/bg.jpg # 既是博客的背景，又是文章默认头图
favicon:
  href: /favicon.ico # 网站图标
  type: image/png # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # 功能开关，可选值（true,false）
  fancybox: true # 灯箱功能
  SmoothScroll: true # 平滑滚动
  pjax: false # Pjax 无刷新加载页面，暂时存在较大问题
  
# 附加图标库 用于自定义字体 www.iconfont.cn 登录->创建项目->添加图标->获取链接
iconlib: # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

cdn: # 这里可以修改站点使用的库的CDN
  mdui:
    css: https://cdn.jsdelivr.net/npm/mdui@0.4.3/dist/css/mdui.min.css
    js: https://cdn.jsdelivr.net/npm/mdui@0.4.3/dist/js/mdui.min.js
  jquery:
    js: https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js
  fancybox:
    css: https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
    js: https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
  SmoothScroll:
    js: https://cdn.jsdelivr.net/npm/smoothscroll-for-websites@1.4.9/SmoothScroll.min.js
  pjax:
    js: //cdn.jsdelivr.net/npm/pjax@0.2.8/pjax.min.js
  lazysizes:
    js: https://cdn.jsdelivr.net/npm/lazysizes@5.1.0/lazysizes.min.js
  highlight:
    css: https://cdn.jsdelivr.net/npm/highlight.js@9.16.2/styles/atom-one-dark.css
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.16.2/build/highlight.min.js
  disqusjs: 
    css: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqusjs.min.css
    js: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqus.min.js
  gitalk:
    css: https://cdn.jsdelivr.net/npm/gitalk@1.5.0/dist/gitalk.min.css
    js: https://cdn.jsdelivr.net/npm/gitalk@1.5.0/dist/gitalk.min.js
  valine:
    js: https://cdn.jsdelivr.net/npm/valine@1.3.9/dist/Valine.min.js  
  copy: https://cdn.jsdelivr.net/gh/xtaodada/xtaodada.github.io@0.0.2/copy.js

menu:
  回到首页: 
    - /
    - icon-home
  # 文章归档: 
  #  - /archives
  #  - icon-container
  关于博客:
    # - /about.html
    - /about/
    - icon-battlenet
  面试相关:
    - /interview/  
    - icon-container
  算法总结:
    - /algorithm/
    - icon-areachart
  项目总结:
    - /project/ 
    - icon-calendar-fill
  文件分享:
    - /sharing/
    - icon-telegram
  简历投递:
    - /hiring/
    - icon-mail-fill
  实时代码统计:
    - /coding/
    - icon-time-circle-fill
  日本語勉強について:
    - /japanese/
    - icon-left
  友情链接: 
    # - /PY.html
    - /py/
    - icon-dribbble

widgets:
- social
- search
- tagcloud
- category
- archive
- recent_posts

maxTagcloud: 0  # 0 表示不限制


# 目录设置
toc:
  enable: false
  maxdepth: 3
  class: origin-toc
  slugify: transliteration
  decodeEntities: true
  anchor:
    position: after
    symbol: '#'
    style: header-anchor

social:
  哔哩哔哩:
    - https://space.bilibili.com/23364338
    - icon-bilibili
    - rgb(231, 106, 141)
    - rgba(231, 106, 141, .15)
  GitHub:
    - https://github.com/jasonkayzk/
    - icon-github
    - rgb(25, 23, 23)
    - rgba(25, 23, 23, .15)
  Twitter:
    - "https://twitter.com/Jasonkay_ZK/"
    - icon-twitter
    - rgb(29, 161, 242)
    - rgba(29, 161, 242, .1)
  Mail:
    - "mailto:271226192@qq.com"
    - icon-mail-fill
    - rgb(29, 161, 242)
    - rgba(29, 161, 242, .1)
  

site_verification: # 向搜索引擎验证你对站点的所有权，用于向搜索引擎提交 sitemap 和管理站点被搜索引擎收录的情况。
  google:
  baidu:

analytics: # 统计系统，目前支持 Google analytics.js 统计、Google Tag Manager 统计、CNZZ 统计、腾讯统计、51.La统计、百度统计
  google_site_id: #<ID>
  gtags_site_id: #<ID>
  cnzz_site_id: #<ID>
  tencent_site_id: #<ID>
  la_site_id: #<ID>
  baidu_site_id: 5f5ec71a32c11ff54dff64d0341017b0 #<ID>
  gtm_container_id: #<ID>

comment: valine # 评论框，目前支持 gitalk,gitment,valine,disqus,disqusjs,changyan,livere,DiscussBot

gitalk:
  admin: nexmoe # 拥有对该repo进行操作的 GitHub username
  owner: nexmoe # 持有该 repo 的 GitHub username
  repo: nexmoe.github.io # 存放评论的 issue 所在的 repo
  clientID: 80b2453b6d5f37ad6225 # GitHub Client ID
  clientSecret: 43e99fa852795c9a7b3eb924b2558c64b84bbdeb # GitHub Client Secret

gitment:
  owner: nexmoe # 持有该 repo 的 GitHub username
  repo: nexmoe.github.io # 存放评论的 issue 所在的 repo
  clientID: 80b2453b6d5f37ad6225 # GitHub Client ID
  clientSecret: 43e99fa852795c9a7b3eb924b2558c64b84bbdeb # GitHub Client Secret

valine:
  enable: true
  appId:  Ak9ceXVMoxs53V6ClY9mtxaC-gzGzoHsz
  appKey: R3dlvrMMwjNhbpBvABQdM3Tm
  notify: true # mail notifier , https://github.com/xCss/Valine/wiki
  verify: true # Verification code
  placeholder: ヾﾉ≧∀≦)o来啊，快活啊! 
  guest_info: nick,mail,link
  pageSize: 10
  avatar: mp
  visitor: true # 阅读量统计

disqusjs:
  shortname: <shortname> # 你的 Disqus shortname
  sitename: <sitename> # 你站点的名称，将会显示在「评论基础模式」的 header 中；该配置应该和 Disqus Admin - Settings - General - Website Name 一致
  api: https://disqus.skk.moe/disqus/ # DisqusJS 请求的 API Endpoint，通常情况下你应该配置一个 Disqus API 的反代并填入反代的地址。你也可以直接使用 DISQUS 官方 API 的 Endpoint https://disqus.com/api/，或是使用SukkaW搭建的 Disqus API 反代 Endpoint https://disqus.skk.moe/disqus/。
  apikey: <api_key> # DisqusJS 向 API 发起请求时使用的 API Key，你应该在配置 Disqus Application 时获取了 API Key;DisqusJS 支持填入一个 包含多个 API Key 的 Array，在每次请求时会随机使用其中一个；如果你只需要填入一个 API Key，则可以填入 String 或 Array。
  admin: <admin> # 你的站点的 Disqus Moderator 的用户名（也就是你的用户名）。你可以在 Disqus - Settings - Account - Username 获取你的 Username
  adminLabel: <adminLabel> # 你想显示在 Disqus Moderator Badge 中的文字。该配置应和 Disqus Admin - Settings - Community - Moderator Badge Text 相同


DiscussBot:
  id: <id> # 站点id
  comments: 50 # 可能是限制每位用户单页面评论最多条数？
  color: # 评论框主色调
  dislike: 0 # 显示差评按钮
  icons: 0 # 图标主题
  diff: 0 # 每位用户name不同颜色

copyright: '<strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可'

# 站内搜索
search:
  path: https://cdn.jsdelivr.net/gh/jasonkayzk/JasonkayZK.github.io@master/search.xml
  field: post

rss: /atom.xml
